travis:
  secure:
    BINSTAR_TOKEN: dOFkjHNESUC08W40Ew0p9KXBY4Fq00A1pQta9F1hxcKsBzCYPnDVDzOChC+3lZntzpgUg2hC8omIe13LlfGinxHyUnhhFsz0gR0fzlVbh0/mLqeQz7AmU7ix0UZUFjuMuk0y2mS0uD9ADIY/46CWXtw4X9upJMGfLOVFe4ZTemwkp5BveDanL1Or21/eExIK8Vf0tyEcBVTG2XZyuEjEJEcTtluZNuRBqNC7k+vWP+p6FQpGHlLlOAxxXRXfML7P5h83RAHcRTOuZicLMpOIxGGoCFWKjPldN5fsC70uzYyFIWgabMMoHE0U/HUffz1fF0r2azWTEbQ3rcPMIN5knKXbS7fZzBBsyoVwUO6nHIqZJyKbrRs7VQLIqInGE7k0OduCEC640P+0O5+faodqXCjnPEFvxt4R+tajcOZR8RfTc11xJrLUFT//FT4Qjk0S0MS6BNuO99gF84ARc5/QSXJjgpnJ0Q0RLsXuyFlwCru4+sgQk9zRPPLDx/ksR8ch+vgJjk8V53g+X2SPjcy5cyWqYU8b57FUHKdVLsoqmfp6KldcD/wX2m8Brgntn2kPJzHO2ByhHiVZgbchCoDMpjCfpnKRjlz1CMj9HEVUPZNuwv2A5RabNP8LaNyxAUkkSMy9Ki9EeCTELUQlOrD3PJ79phB1CHeepNYm49k2y3g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
